
package webservice.jde.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceSoap {



    @WebMethod(action = "http://tempuri.org/mainWebService")
    @WebResult(name = "mainWebServiceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mainWebService", targetNamespace = "http://tempuri.org/", className = "webservice.jde.service.MainWebService")
    @ResponseWrapper(localName = "mainWebServiceResponse", targetNamespace = "http://tempuri.org/", className = "webservice.jde.service.MainWebServiceResponse")
    public String mainWebService(
            @WebParam(name = "DBNsp", targetNamespace = "http://tempuri.org/")
                    String dbNsp,
            @WebParam(name = "sType", targetNamespace = "http://tempuri.org/")
                    String sType,
            @WebParam(name = "sWhere", targetNamespace = "http://tempuri.org/")
                    String sWhere);


    @WebMethod(action = "http://tempuri.org/mainPdfWebService")
    @WebResult(name = "mainPdfWebServiceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mainPdfWebService", targetNamespace = "http://tempuri.org/", className = "webservice.jde.service.MainPdfWebService")
    @ResponseWrapper(localName = "mainPdfWebServiceResponse", targetNamespace = "http://tempuri.org/", className = "webservice.jde.service.MainPdfWebServiceResponse")
    public byte[] mainPdfWebService(
            @WebParam(name = "DBNsp", targetNamespace = "http://tempuri.org/")
                    String dbNsp,
            @WebParam(name = "sType", targetNamespace = "http://tempuri.org/")
                    String sType,
            @WebParam(name = "sWhere", targetNamespace = "http://tempuri.org/")
                    String sWhere);

}
